Refactor:Order Service Testing
SDPM-lab/Anser pull request #19
Opened 2023-02-06 15:45 UTC by kai890707

**Description**

1. Refactor order service testing.

**Checklist:**
- [ ] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] Conforms to style guide

2023-02-06 20:14 UTC, ping-yee requested changes
There are some little changes need to be handled.

2023-02-06 20:14 UTC, ping-yee commented on develop/tests/API/v2/OrderTest.php
> +    public function testIndexOrderNotHasParametersSuccess()
Change Not has to without.

2023-02-06 20:14 UTC, ping-yee commented on develop/tests/API/v2/OrderTest.php
> +    public function testIndexOrderNotHasParametersFail()
Ditto.

2023-02-07 04:22 UTC, kai890707 commented on develop/tests/API/v2/OrderTest.php
> +    public function testIndexOrderNotHasParametersSuccess()
This change is done.

2023-02-07 04:22 UTC, kai890707 commented on develop/tests/API/v2/OrderTest.php
> +    public function testIndexOrderNotHasParametersFail()
This change is done.

2023-02-07 08:09 UTC, ping-yee reviewed
LGTM

2023-02-07 08:10 UTC, ping-yee approved these changes
LGTM

2023-02-07 08:10 UTC, merged